name: Build Snow

on:
  push:
    branches: [ "master" ]
    paths:
    - 'src/**'
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5 
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1
    - name: Restore Packages
      run: nuget restore src/Sandra.Snow.sln
    - name: Build solution
      run: msbuild src/Sandra.Snow.sln -t:rebuild -property:Configuration=Release
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
      # Artifact name
        name: Snow
        # A file, directory or wildcard pattern that describes what to upload
        path: src/Snow/bin/Release
