name: Publish Website

on: 
  push:
    paths:
      - 'SnowSite/**'
      - '.github/workflows/publish-website.yml'
  workflow_dispatch:
  workflow_run:
    workflows: ["Build Snow"]
    types:
      - completed

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Checkout SnowSite
        uses: actions/checkout@v3
        with:
          sparse-checkout: SnowSite
          path: doc
      - name: Checkout Website
        uses: actions/checkout@v3
        with:
          repository: ${{ env.WEBSITE_REPO }}
          path: website
          token: ${{ secrets.WEBSITE_PAT }}
      - name: Download Snow artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-snow.yml
      - name: run Snow
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $blogDir = (mkdir ".\website" -force).FullName
          $docDir = ".\doc\SnowSite"

          "Configuring git..."

          pushd $docDir
          $lastMessage = git log -1 --pretty=%B | Select-Object -First 1
          $lastUserName = git log -1 --pretty=format:'%an' | Select-Object -First 1
          $lastUserEamil = git log -1 --pretty=format:'%ae' | Select-Object -First 1

          git config --global user.name "github actions bot (on behalf of $lastUserName)"
          git config --global user.email $lastUserEamil
          git config --global core.autocrlf false
          popd

          "Overriding output dirs to $blogDir"
          $configPath = "$docDir\Snow\Snow.config.json"
          $config = Get-Content $configPath | ConvertFrom-Json
          $config.postsOutput = $blogDir
          $config.pagesOutput = $blogDir
          $config | ConvertTo-Json | Out-File $configPath

          "Running Snow..."
          & Snow\Snow.exe "config=$configPath"

          Write-Output "Updating $blogdir..."
          cd $blogdir
          Get-Location #DEBUG

          git add .
          git commit -m "Publish: $lastMessage"
          git push
