name: Publish PxtlCa

on: 
  push:
    paths:
      - 'SnowSite/**'
      - '.github/workflows/*'
  workflow_dispatch:
  workflow_run:
    workflows: ["Build Snow"]
    types:
      - completed

jobs:
  publish:
    runs-on: windows-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout SnowSite
        uses: actions/checkout@v3
        with:
          sparse-checkout: SnowSite
          path: doc
      - name: Checkout Pxtl.github.io
        uses: actions/checkout@v3
        with:
          repository: Pxtl/Pxtl.github.io
          path: Pxtl.github.io
      - name: Download Snow artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-snow.yml
      - name: run Snow
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'

          "Configuring git..."

          $lastMessage = git log -1 --pretty=%B | Select-Object -First 1
          $lastUserName = git log -1 --pretty=format:'%an' | Select-Object -First 1
          $lastUserEamil = git log -1 --pretty=format:'%ae' | Select-Object -First 1

          git config --global user.name "github actions bot (on behalf of $lastUserName)"
          git config --global user.email $lastUserEamil

          "Running Snow..."
          & Snow\Snow.exe config=.\doc\SnowSite\Snow\Snow.config

          Write-Output "Updating Pxtl.github.io..."
          cd Pxtl.github.io
          
          git add .
          git commit -m "Publish: $lastMessage"
          git push
