name: publish PxtlCa

on: 
  push:
    paths:
      - 'SnowSite/**'
      - '.github/workflows/*'
  workflow_dispatch:
  workflow_run:
    workflows: ["Build Snow"]
    types:
      - completed

jobs:
  publish:

    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: SnowSite
      - name: Download Snow artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-snow.yml
      - name: run Snow
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          tree #debug
          ls #debug
          ls SnowSite/Snow #debug
          "Running Snow"
          & Snow\Snow.exe config=.\SnowSite\Snow\Snow.config
