name: publish PxtlCa

on: [ push ]

jobs:
  publish:

    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          filter: SnowSite/**
      - name: Download Snow artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-snow.yml
      - name: run Snow
        shell: pwsh
        run: |
          ls
          "Running Snow"
          & Snow\Snow.exe
