name: Publish PxtlCa

on: 
  push:
    paths:
      - 'SnowSite/**'
      - '.github/workflows/*'
  workflow_dispatch:
  workflow_run:
    workflows: ["Build Snow"]
    types:
      - completed

jobs:
  publish:
    runs-on: windows-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout SnowSite
        uses: actions/checkout@v3
        with:
          sparse-checkout: SnowSite
      - name: Checkout Pxtl.github.io
        uses: actions/checkout@v3
        with:
          repository: Pxtl/Pxtl.github.io
          path: ..
      - name: Download Snow artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-snow.yml
      - name: run Snow
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          
          ls .. #debug
          "Running Snow..."
          & Snow\Snow.exe config=.\SnowSite\Snow\Snow.config
          "Checking output..."
          ls .. #debug
